### ISSUE TITLE
Additional maintainers for the project.

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/svglint#31]
_Original below_

Per [this comment](https://github.com/birjj/svglint/issues/31#issuecomment-1783384128), I'd be looking for new maintainers. While I will try to keep up maintenance for a bit, my intention is to stop maintenance of this project since I'm not using it in any capacity anymore and am too unfamiliar with the code base to make/review major changes.

Since I'm not the owner of this project, I'll defer any decisions about it's future direction in terms of maintenance to @birjj. 

---

### Original comment

As noted in [this comment](https://github.com/birjolaxew/svglint/issues/11#issuecomment-780524275) and  [this comment](https://github.com/birjolaxew/svglint/issues/30#issuecomment-857725722) the current maintainer of this project is currently too  busy to maintain this project fully. [I already offered to help earlier](https://github.com/birjolaxew/svglint/pull/22#issuecomment-834633173) but I guess this comment was missed because that PR was ignored, hence this issue.

I think it would be nice to have at least one more maintainer for this project that can review Pull Requests and get out patches. In particular now that [the NPM package has a transitive dependency with a known vulnerability](https://user-images.githubusercontent.com/3742559/121437377-81782c00-c982-11eb-8d15-e78bafd7527b.png). Again I, and I think other members of the [simple-icons](https://github.com/simple-icons/simple-icons) project, would be happy to help out given our reliance on this tool - but of course I would encourage others that want to help out to volunteer as well :slightly_smiling_face:

**Comment by birjolaxew** [comment]
Sorry, I completely missed that comment. I've taken to ignoring any notifications for dependabot PRs since I don't have time to release anything, so the message got caught in that.

I'd be happy to add another maintainer if anyone's interested in volunteering.

**Comment by ericcornelissen** [comment]
I went ahead and did a review of all open Pull Requests for dependencies and created an extra one for another vulnerability in a dependency. If you find the time you should be able to merge them - or at least the ones that are important, as per my comments - and trigger a new release. If not, you can add me as a collaborator to this project if you want, then I can do it. I'll also try to start looking into the open issues in the coming days as well.

---

Quick side note on other dependencies with a vulnerability: The transitive vulnerable dependency `trim-newlines` requires upgrading `meow` to 10.0.1 but it seems that version is only published as an ES module making it incompatible with the current code base (not to mention it's 7 major versions ahead of the current `meow` dependency). This will either have to wait for the TypeScript rewrite or at least a rewrite of `bin/cli.js` to allow it to import ES modules (other modules in this project don't _need_ to be rewritten as ES Modules can import CommonJS modules).

**Comment by birjolaxew** [comment]
I'll be closing this since I've invited @ericcornelissen as a maintainer for now. Thanks a lot for helping out!

I've opened #34 to discuss the `meow` dependency.

**Comment by ericcornelissen** [comment]
Re-opening this as I'd be looking for a new maintainer to take over my role. \cc @birjj

**Comment by birjj** [comment]
Sorry for the late response.

My life has changed enough that I don't feel I'm in a good place to act as maintainer of an OSS project. The work you've done is incredibly appreciated - without it, the project would've likely been archived.

It looks like the Simple Icons team are the primary contributors currently. Would you be interested in transferring the repo to the Simple Icons organization to formalize that?

**Comment by birjj** [comment]
Pinging current Simple Icons members (@modeja, @PeterShaggyNoble, @LitoMore). Is there interest in the organization taking over the svglint project?

**Comment by mondeja** [comment]
I personally agree. Seems that simple-icons is the main consumer of the library.

**Comment by LitoMore** [comment]
My pleasure.

**Comment by birjj** [comment]
Nice! It'll be great for the project to find an organizational home, so it isn't just left for dead.  
There are two permission things to iron out in the process:

1. It looks like I need "permission to create publish repositories on simple-icons" to transfer the project. Presumably the only way to do this is for me to temporarily join the simple-icons organization?
1. For the NPM package, we'll need to decide on a maintainer from the Simple Icons team to add - preferably one that's already listed as a maintainer on the `simple-icons` NPM package itself, to avoid any trickery.

I don't know if there's a good place to coordinate this on GitHub (unless it's a few short comments, I suppose), but I can be reached by e-mail at johanringmann@gmail.com if you'd prefer.

**Comment by mondeja** [comment]
Okay, I've invited you temporarily as a maintainer of simple-icons. Let me know if you still have no rights to transfer the repo.

**Comment by birjj** [comment]
I've transferred the svglint repo, and left the organization. Thanks @mondeja! :tada:

As for the NPM package, I've invite you (`~mondeja` on NPM) as a maintainer. Once accepted, that should complete the transfer to the simple-icons team.

**Comment by mondeja** [comment]
Great, I've accepted the invitation. Thanks for your hard work until now with this awesome tool. If you want to return to the organization in the future, do not hesitate to contact us. Cheers!
